### ISSUE TITLE
Pre-trained models

### ISSUE THREAD

**Issue by chensjtu** [dimitrisPs/msdesis#1]
thanks for the sharing! I wonder the name of Pre-trained models means, i.e. 
<img width="148" alt="image" src="https://github.com/dimitrisPs/msdesis/assets/38242929/cb579694-cb01-47bd-b1f7-9485b40d1501">
what does these ckpts mean?

**Comment by dimitrisPs** [comment]
Hello,
No worries at all, we hope the project helps you. 
The name of the folders combined with the name of their parent directory correspond to the different training modes introduced in section V.A of the MSDESIS paper and should reproduce the results from Table I.
